[package]
name = "rust-hello-world"
version = "0.1.0"
authors = ["Giuseppe Burtini <giuseppe@burtini.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.2"

[[bin]]
name = "rust-hello-world"
path = "src/main.rs"
